version: "3.7"

services:
  app:
    init: true
    build:
      dockerfile: Dockerfile
    volumes:
      - ../app:/app

  nginx:
    image: nginx:1-alpine
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf